### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by fulldecent** [mlisik/MRLCircleChart#70]
Please add screenshots to the readme

**Comment by mlisik** [comment]
Thanks for the nudge, @fulldecent -- needed that to get back to work on polishing this demo a bit. Since there's already an issue with a list of general README improvements, though, I'll close this in favour of #40.

**Comment by mlisik** [comment]
Thanks for the nudge, @fulldecent -- needed that to get back to work ;) 
Since there's already an issue waiting with some overall readme improvements listed, though, I'll close this in favour of #40.
