### ISSUE TITLE
Crash when 1 segment

### ISSUE THREAD

**Issue by bblok11** [mlisik/MRLCircleChart#88]
When my data source has only one segment, there is a crash on `ChartView.reloadData` because the `colorPalette` has 0 items. In the `UIColor.colorRange` extension, an empty array is returned when there is only 1 item, while the extension promises to return the same number of items as the `count` parameter.

**Comment by mlisik** [comment]
Hi @bblok11, I've opened a PR with a fix if you want to take a look -- will merge it in later today and push 0.5.1 to cocoapods trunk. Have to check first if I want to update dependencies etc - it's been a while since 0.5.0.

**Comment by bblok11** [comment]
Great, that should fix it. Thank you man!

**Comment by mlisik** [comment]
It's part of 0.5.1, available now :)
