### ISSUE TITLE
Clockwise animation for not full circle

### ISSUE THREAD

**Issue by borisyurkevich** [mlisik/MRLCircleChart#92]
When animating from zero to max, it works correctly, in clock wise direction.
However, given max value of 1000, trying to make it go from zero to 600. What it does instead, it goes from max to 600 in counterclockwise direction. I only need one data segment. Am I missing something obvious?

**Comment by borisyurkevich** [comment]
For now, setting start and finish to `0` helped to solve my problem.

    if animated {
          layer.animateInsertion(
            // source.isFullCircle() ? 0 : source.startAngle(for: index), endAngle: source.isFullCircle() ? 0 : .pi * 2
            0, endAngle: 0
          )
    }

**Comment by mlisik** [comment]
Hi! The counter clockwise animation for full circle is left over from the requirements we had for the original project... But the lib doesn't need to support that anymore and I'll be happy to change it to match the (more natural) behaviour you have in mind. 

The above approach with 0,0 will work fine if you have one segment, but I would need to rethink a few bits and pieces to cover other scenarios, like adding segments dynamically vs inserting more than one at the same time - I've a wip implementation of that but I'll put some time in untangling that longish `reloadData()` func before I'll push it up - hopefully after the weekend.
